spring:
  application:
    name: moderation-service

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:default}

  config:
    import: "configserver:"
  cloud:
    config:
      uri: http://config-server:8888
      failFast: false  # Don't fail immediately if the config server isn't available
      retry:
        maxAttempts: 10
        initialInterval: 1000
        multiplier: 2
        maxInterval: 5000